### ISSUE TITLE
Want help on maintenance?

### ISSUE THREAD

**Issue by pi0** [wooorm/import-meta-resolve#11]
Hi dear @wooorm and thanks for your nice package ❤️ 

We have adopted `import-meta-resolve` (inline for packaging issues) for [unjs/mlly](https://github.com/unjs/mlly) that is used by nuxt and some other libs with over 1.5M monthly downloads. 

I have discovered there are some upstream fixes in Node.js that need to be applied to both packages (here is a summary: https://github.com/unjs/mlly/issues/134). I thought it would be a good chance to move import-meta-resolve to unjs ecosystem to make sure both packages leverage from latest updates and also allowing to use it as external package for mlly. 

If you prefer not to, i will remember to make a backport PR for upstream changes.

Cheers.

**Comment by wooorm** [comment]
Hi there Pooya!

All of those patches you list are already in this project, I just checked and there were only 3 commits of note in the last 2 months, that are only refactoring some internals around and changing an error message: https://github.com/wooorm/import-meta-resolve/commit/05c1beafc0711cc06b86f9fde417947c0bff2973.

If those earlier commits are not in your package, I recommend improving your inlining script to pull in changes from this repo. Something like this in a build script:
```sh
npx esbuild import-meta-resolve --bundle --platform=node --outfile=vendor/import-meta-resolve.js
```

Some of the commits you refer to work on experimental features, such as importing from HTTPS, which then requires features to “allowlist” domains and SHA checking of resources and such. Such code is not implemented here: a) that’s a *ton* of code, b) it’s super volatile and buggy, c) it changes so much.

So I don’t see a problem with how this project is maintained. I don’t see a reason to move it somewhere else. Though, of course, you are welcome to help maintain this project. I timed myself and it took me 20 minutes to check and port all changes.

**Comment by pi0** [comment]
Thanks so much for working on patches dear @wooorm ❤️ If this package could export dual cjs/mjs build i would directly use it. mlly can be `require`ed too. So in the meantime will manually make sure to keep it updated.

**Comment by wooorm** [comment]
I am not interested in shipping CJS.

It is possible to use a dynamic import expression in CJS. As `resolve` is async anyway, you could use:

```js
/**
 *
 * @param {string} specifier
 * @param {string} url
 */
async function mllyResolve(specifier, url) {
  return import('import-meta-resolve').then((mod) =>
    mod.resolve(specifier, url)
  )
}
```

**Comment by pi0** [comment]
Yes, I'm aware of this possibility but the current version of mlly, also exports sync resolve methods for backward compatibility (undocumented). I am going to inline node dependency on the build to avoid copying the source for now (https://github.com/unjs/mlly/commit/41a5ba135e4f36e49a1bcd5acc39161b26b9d26b). Maybe later drop sync and do this. Thanks!
