### ISSUE TITLE
`import.meta.resolve` is now defined to be _sync_

### ISSUE THREAD

**Issue by giltayar** [wooorm/import-meta-resolve#14]
You can see it here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import.meta/resolve

And also in Node.js, where a PR just changed it to be synchronous: https://github.com/nodejs/node/pull/44710

I can create a PR for this, if you wish. Just checking that it's OK.

**Comment by wooorm** [comment]
Hey Gil!

Oh, nice! This should be pretty straight forward in the API.
But not so sure about making the tests and the infra work: https://github.com/wooorm/import-meta-resolve/blob/4831612957ab3465cd7c3c1b6fc4db85984de979/.github/workflows/main.yml#L23-L24.
And I guess this is a breaking change?

Anyway, yeah: PR would be great, thank you!
