### ISSUE TITLE
Possible to use worker threads and execArgv?

### ISSUE THREAD

**Issue by jcbhmr** [wooorm/import-meta-resolve#17]
In theory, I think the following is possible:

```js
export default function resolve(specifier, parentURL = undefined) {
  if (parentURL == null) {
    if (this?.url != null) {
      parentURL = this.url
    } else {
      parentURL = getParentURLUsingErrorStack()
    }
  }
  const sab = new SharedArrayBuffer(4)
  const lock = new Int32Array(sab)
  const worker = new worker_threads.Worker(`
    const sab = worker_threads.workerData
    const lock = new Int32Array(sab)
    worker_threads.parentPort.on("message", ([specifier, parentURL]) => {
      const resolved = await import.meta.resolve(specifier, parentURL)
      worker_threads.parentPort.postMessage(resolved)
      Atomics.store(lock, 0, 1)
      Atomics.notify(lock, 0)
    })
  `, {
    eval: true,
    //          👇 This is the cool idea? Maybe this works?
    execArgv: ["--experimental-import-meta-resolve", ...process.execArgv],
    workerData: sab
  })
  worker.postMessage([specifier, parentURL])
  Atomics.wait(lock, 0, 0)
  return recieveMessageOnPort(worker)
}
```

_No this code doesn't work as-is._

```js
import resolve from "import-meta-resolve"
import.meta.resolve = resolve;

console.log(import.meta.resolve("my-npm-package"))
//=> 'file:///node_modules/my-npm-package/index.js'
```

Obviously there's some hiccups that would need to be finagled with and solved, but I think this might work!

**Comment by jcbhmr** [comment]
To answer the question: yes, this is definitely possible. It works! https://github.com/jcbhmr/import-meta-resolve

**Comment by wooorm** [comment]
I’m not sure what your question is? Looks like you made a completely different project that solves your needs?

**Comment by wooorm** [comment]
Ah, right, yeah. The pros of this package you list are indeed why this exists. The previous version supports Node 12 too btw.

But I don’t get why you need your thing? At that point, pass the `--experimental-import-meta-resolve` flag?

**Comment by jcbhmr** [comment]
It's not synchronous in Node.js v16 or v18. Only v20 matches the browser synchronous behavior

**Comment by jcbhmr** [comment]
You know, now that I think about it, you could actually get it to work with conditions too! You just pass in a `-C my-condition` flag to execArgv in the worker_threads.Worker constructor like this:

Also with regards to Node.js v12 support, import.meta.resolve() **is available behind `--experimental-import-meta-resolve`** in Node.js v12 according to MDN:

<details>

![image](https://github.com/wooorm/import-meta-resolve/assets/61068799/94b240a1-aff1-46eb-b02a-4a3410c5df94)

</details>

I think that it would definitely be possible to keep the same API surface (resolve and moduleResolve()) by taking advantage of the worker method. For the moduleResolve() API the two execArgv flags are `-C` and `--preserve-symlinks`. That's it!

<details>

https://nodejs.org/api/cli.html#--preserve-symlinks
![image](https://github.com/wooorm/import-meta-resolve/assets/61068799/a37a6d40-8f88-4a09-951b-bfeebd32da34)

https://nodejs.org/api/cli.html#-c-condition---conditionscondition
![image](https://github.com/wooorm/import-meta-resolve/assets/61068799/760a008e-2e55-4eae-87a4-d227eb2574de)

</details>

Idea:

```js
import worker_threads from "node:worker_threads";

const workerCode = `
import worker_threads from "node:worker_threads";
worker_threads.parentPort.on(
  "message",
  /** @param {[Int32Array, string, string | undefined]} $1 */
  async ([lockBuffer, specifier, parentURL]) => {
    const lock = new Int32Array(lockBuffer);
    /** @type {[string] | [void, any]} */
    // @ts-ignore
    let r = [];
    try {
      r[0] = await import.meta.resolve(specifier, parentURL);
    } catch (e) {
      r[1] = e;
    }
    worker_threads.workerData.port.postMessage(r);
    Atomics.store(lock, 0, 1);
    Atomics.notify(lock, 0);
  }
);
`;

const execArgv = ["--experimental-import-meta-resolve"]
if (conditions) {
  for (const condition of conditions) {
    execArgv.push("-C")
    execArgv.push(condition)
  }
}
if (preserveSymlinks) {
  execArgv.push("--preserve-symlinks")
}

    const u =
      "data:text/javascript;base64," +
      Buffer.from(workerCode).toString("base64");
    const worker = new worker_threads.Worker(`import(${JSON.stringify(u)})`, {
      eval: true,
      execArgv,
      name: "import-meta-resolve",
    });
    worker.unref();

// Then...

  const lockBuffer = new SharedArrayBuffer(4);
  const lock = new Int32Array(lockBuffer);
  worker.postMessage([lockBuffer, specifier, parentURL]);
  Atomics.wait(lock, 0, 0);
  const r = receiveMessageOnWorker(worker).message;

  if (r.length == 1) {
    return r[0];
  } else {
    throw r[1];
  }
```

**Comment by wooorm** [comment]
> --experimental-import-meta-resolve

Yep, the flag works everywhere!

And: assuming you can go with `await`, `const x = await whatever` is the same as `const x whatever`. so Node 12 with await works the same as Node 20 with await.

---

Personally I’m fine with you shelling out in your version, and if everyone wants to use that, that’s fine. I’d like to remain in the same thread for this if possible and to provide a lower-level primitive!

**Comment by jcbhmr** [comment]
> I’d like to remain in the same thread for this if possible and to provide a lower-level primitive!

If I were to open a PR that maintained the API surface as-is and used workers instead of shim code, would it be considered? 🤔

_In case you missed it: https://github.com/wooorm/import-meta-resolve/issues/17#issuecomment-1622517410_

**Comment by wooorm** [comment]
I don’t think it’s a good idea for everyone. There are significant trade-offs.
There has been no discussions on whether the tests pass, what the performance implications are. The flag remains experimental, using it is still experimental, this currently works, and it will probably be fine in the future, but Node can change it in any version, this project currently adheres to semver instead and provides the same version everywhere. There would also need to be a discussion based on whether people *want* to use existing loaders and conditions, or whether they want to replace or merge them.

Based on the outcome of those discussions, perhaps it can indeed be replaced, but it is also possible to have two projects that exist, or to have two versions maintained in this project.

**Comment by jcbhmr** [comment]
Sounds good. 👍

**Comment by jcbhmr** [comment]
📬 Wanted to update you: I've published a (reasonably) polished package at https://github.com/webfill/import-meta-resolve and https://www.npmjs.com/package/@webfill/import-meta-resolve. It's a bit more than just a worker-based Node.js `import.meta.resolve()` shim as I alluded to in my previous comments since it tries to unify `import.meta.resolve()` across Node.js Deno Bun and the browser to make them all support _at least_ this signature:

```ts
// NOT a promise!
function import.meta.resolve(specifier: string): string;
```

**Comment by wooorm** [comment]
Oh wow, that looks involved!

I’m already maintaining a ton of code, I don’t have much bandwidth to maintain more, and this project is currently suiting my needs. But, depending on the discussion points in my [previous comment](https://github.com/wooorm/import-meta-resolve/issues/17#issuecomment-1623151410), it could perhaps be housed here. But it doesn’t have to be at all!

**Comment by jcbhmr** [comment]
> Oh wow, that looks involved!

It's honestly not 🤣 src/ only looks complex because there's 3x different special cases (all under 10 lines) to remap things like `import.meta.resolveSync` to import.meta.resolve. also a few of those files are literally empty because browser and deni require zero patching 😜 point is it's ~on-par with something like https://github.com/sindresorhus/tempy#readme fore complexity imo

> I’m already maintaining a ton of code, I don’t have much bandwidth to maintain more

That's ok the offer was also kinda a  "I trust you; so if you spot an error in this cool thing I made you can patch it without the 3day back-and-forth issue pr communication dance thate usually happens 😆" <sup>so yah if you ever spot an error or whatever you've got merge priv 👍</sup>

> But, depending on the discussion points in my previous comment, it could perhaps be housed here.

Bruh that was the goal lmao 🤣 what needs to be done to make that happen?

**Comment by wooorm** [comment]
It’s all in that last comment! https://github.com/wooorm/import-meta-resolve/issues/17#issuecomment-1623151410 Discussions on things!
