### ISSUE TITLE
Support for resolving modules from folder paths

### ISSUE THREAD

**Issue by fabiospampinato** [wooorm/import-meta-resolve#19]
I spent some time trying to resolve a dependency from a URL like the following, which was a bit confusing because I have that dependency listed in `package.json`, installed in `node_modules` and I can import it from the REPL, but this module can't find it:

```js
url.pathToFileURL(process.cwd());
```

But apparently using a folder's path as the starting point is not supported, while something like this works:

```js
url.pathToFileURL(path.join(process.cwd(), "index.js"));
```

IMO it'd be nice if resolving from a folder was just supported also, or at least if this scenario was documented.

**Comment by nicolo-ribaudo** [comment]
Supporting both folders and files as the base is ambiguous: if both `foo/index.js` and `foo/bar/index.js` exist, what does `resolve("./index.js", "foo/bar")` resolve to?

The readme currently says that the second parameter is "the absolute parent module URL", maybe it should either be made more prominent or more explicit that a module is a file 🤔

**Comment by wooorm** [comment]
I don't see how this issue is here?

Anyway, yeah, its the same as browsers. It matters where you resolve from

**Comment by nicolo-ribaudo** [comment]
In browsers/Node.js `import.meta.resolve` takes a single parameter, so you don't really "notice" that it's the file URL and not the folder URL.

**Comment by fabiospampinato** [comment]
> I don't see how this issue is here?

Right this is maybe out of place 🤔 However, the description is "Resolve things like Node.js.", but when I fire up a REPL and import something what file is Node resolving things from?

**Comment by nicolo-ribaudo** [comment]
https://github.com/nodejs/node/blob/1b60054fffc0c67a711cdf3efbcc8f44afab0ce2/lib/repl.js#L461

`pathToFileURL(path.join(process.cwd(), 'repl'))`, apparently

**Comment by wooorm** [comment]
I think youre looking for import.meta.url? Thats whats also in the docs here as a recommendation

**Comment by fabiospampinato** [comment]
@wooorm yeah but the REPL is a weird environment:

<img width="482" alt="Screen Shot 2023-12-12 at 18 37 36" src="https://github.com/wooorm/import-meta-resolve/assets/1812093/75d5ea98-ed6d-4d54-9ee8-e55cf39cda89">

Anyway, closing this to keep things tidy. Worth thinking about special-casing what happens if the input path is a folder for convenience, either by throwing or by doing something else, imo.

**Comment by wooorm** [comment]
IMO this is all more about how URLs resolve. Where `<a href="x">` goes to. I don’t see the web changing that. It depends on whether you’re on `https://example.com/y` or `https://example.com/y/`:

```js
new URL('x', 'https://example.com/y').href // 'https://example.com/x'
new URL('x', 'https://example.com/y/').href // 'https://example.com/x'
```

> `process.cwd`

You can solve it with `url.pathToFileURL(process.cwd() + path.sep)`.

---

Anyway, this is a copy of Node. Changes go in Node.
