### ISSUE TITLE
Incompatible with yarn P'n'P

### ISSUE THREAD

**Issue by JounQin** [wooorm/import-meta-resolve#23]
Same as #10

See also https://github.com/conventional-changelog/commitlint/issues/3936

I also tried `yarn unplug`:

```json
{
  "dependenciesMeta": {
    "@commitlint/config-conventional": {
      "unplugged": true
    },
    "@commitlint/resolve-extends@19.0.1": {
      "unplugged": true
    },
    "import-meta-resolve": {
      "unplugged": true
    }
  }
}
```

```log
file:///Users/JounQin/.yarn/berry/cache/@commitlint-cli-npm-19.0.1-8d41b28200-10.zip/node_modules/@commitlint/cli/lib/cli.js:129
        throw err;
        ^

Error: Cannot find module "@commitlint/config-conventional" from "/Users/JounQin/Workspaces/GitHub/test"
    at resolveId (file:///Users/JounQin/Workspaces/GitHub/test/.yarn/unplugged/@commitlint-resolve-extends-npm-19.0.1-78a2e74462/node_modules/@commitlint/resolve-extends/lib/index.js:158:17)
    at tryResolveId (file:///Users/JounQin/Workspaces/GitHub/test/.yarn/unplugged/@commitlint-resolve-extends-npm-19.0.1-78a2e74462/node_modules/@commitlint/resolve-extends/lib/index.js:145:12)
    at resolveConfig (file:///Users/JounQin/Workspaces/GitHub/test/.yarn/unplugged/@commitlint-resolve-extends-npm-19.0.1-78a2e74462/node_modules/@commitlint/resolve-extends/lib/index.js:132:20)
    at file:///Users/JounQin/Workspaces/GitHub/test/.yarn/unplugged/@commitlint-resolve-extends-npm-19.0.1-78a2e74462/node_modules/@commitlint/resolve-extends/lib/index.js:96:26
    at Array.reduce (<anonymous>)
    at loadExtends (file:///Users/JounQin/Workspaces/GitHub/test/.yarn/unplugged/@commitlint-resolve-extends-npm-19.0.1-78a2e74462/node_modules/@commitlint/resolve-extends/lib/index.js:95:22)
    at resolveExtends (file:///Users/JounQin/Workspaces/GitHub/test/.yarn/unplugged/@commitlint-resolve-extends-npm-19.0.1-78a2e74462/node_modules/@commitlint/resolve-extends/lib/index.js:76:28)
    at load (file:///Users/JounQin/.yarn/berry/cache/@commitlint-load-npm-19.0.1-947ecbb8ee-10.zip/node_modules/@commitlint/load/lib/load.js:44:28)
    at async main (file:///Users/JounQin/.yarn/berry/cache/@commitlint-cli-npm-19.0.1-8d41b28200-10.zip/node_modules/@commitlint/cli/lib/cli.js:202:20) {
  code: 'MODULE_NOT_FOUND'
}
```

Reproduction: https://github.com/JounQin/test/tree/repro/commitlint

Steps:

1. `yarn install`
2. `yarn commitlint --from`

Related source codes: https://github.com/wooorm/import-meta-resolve/blob/411516aaefa86bbe4d8566a98e79370f78f48338/lib/resolve.js#L994-L1038

**Comment by wooorm** [comment]
It can’t work, see #10.

**Comment by JounQin** [comment]
Yeah, I looked through that issue, and hope the yarn berry team can help.

cc @arcanis @merceyz @paul-soporan @larixer

**Comment by arcanis** [comment]
This isn't a PnP issue, more a missing import-meta-resolve feature (standard Node.js loader support), see https://github.com/wooorm/import-meta-resolve/issues/10#issuecomment-1968499148

**Comment by JounQin** [comment]
I think we'd better discuss in this new issue instead of the closed one.

So I quoted @arcanis's comment here.

> > As I understand it (I backported recent changes just now), loaders are implemented _above_ `resolve`: [nodejs/node@`3ebe753`/lib/internal/modules/esm/loader.js](https://github.com/nodejs/node/blob/3ebe7535b456771078368ba72345f8d2e16ce695/lib/internal/modules/esm/loader.js).
> 
> It's the other way around - `import.meta.resolve` must go through loaders. If it wasn't, calling `import(import.meta.resolve(...))` wouldn't work, which would be unacceptable. You can easily check it:
> 
> ```ts
> import {register} from 'module';
> 
> // export async function resolve() {
> //   return {shortCircuit: true, url: 'file:///lol'};
> // }
> register('data:application/javascript;charset=utf-8,export%20async%20function%20resolve%28%29%20%7B%0D%0A%20%20return%20%7BshortCircuit%3A%20true%2C%20url%3A%20%27file%3A%2F%2F%2Flol%27%7D%3B%0D%0A%7D');
> 
> console.log(import.meta.resolve('foo'));
> ```
> 
> Prints
> 
> ```
> file:///hello
> ```
> 
> In other words, `import-meta-resolve` should implement loader support to be on parity with `import.meta.resolve`, this isn't an issue with PnP itself.

**Comment by wooorm** [comment]
Joun, what you are asking for is that people have to specify `--loader some-yarn-loader` to your commit-lint CLI.
Do you really want that?

**Comment by JounQin** [comment]
@wooorm I don't think that's the solution? `yarn` will call its own `.pnp.loader.mjs` automatically without user action.

**Comment by wooorm** [comment]
Yes that’s a loader. Someone has to use it?
If you want this package to support loaders like Node does, then it would mean someone has to do `commitlint --loader .pnp.loader.mjs`?

**Comment by wooorm** [comment]
It sort of does that. It can’t exactly, because your CLI calls Node: https://github.com/conventional-changelog/commitlint/blob/87b1d36d23005b9c1d010ff6a49d1de7f4888cfe/%40commitlint/cli/cli.js.
Yarn is injecting environment variables.
So using Yarn like this means you can’t use `node`. Jeez.
Is that normal for Yarn users? That they can’t call `commitlint`? They have to wrap it in `yarn commitlint`?

---

Use `import.meta.resolve`. Don‘t use this package. The readme says that no loaders (and no env variables) are supported: https://github.com/wooorm/import-meta-resolve#differences-to-node.

`import.meta.resolve` is stable now. Loaders are incredibly complex. You are free to try it, I think it would be another project the size of this one.
There are use cases when you do or don’t want loaders. I like not having to load all that code to support loaders.

**Comment by JounQin** [comment]
What do mean by

> So using Yarn like this means you can’t use node

There is `yarn node`

> Is that normal for Yarn users? That they can’t call commitlint? They have to wrap it in yarn commitlint?

When use yarn, the user must use `yarn commitlint`, like `npx commitlint`, there is no `yarn global` binaries anymore.

---

> Use import.meta.resolve. Don‘t use this package. 

I'd love to, but we're still targeting on Node < 20, and the second parameter is still experimental.

> There are use cases when you do or don’t want loaders. I like not having to load all that code to support loaders.

Understand, I'm fine with not supporting loaders(or yarn P'n'P actually) personally.

**Comment by wooorm** [comment]
I think it’s interesting, the Yarn PnP thing. But it intentionally does lots of things differently. As you show, it has to wrap CLIs and `node` itself. So it’s not going to work with several tools.

As for supporting loaders, I think it would be *a lot* of work. Also to maintain. I don’t think anyone is interested in doing that work. See https://github.com/wooorm/import-meta-resolve/issues/10#issuecomment-1968831154.
