### ISSUE TITLE
Async API for moduleResolve()?

### ISSUE THREAD

**Issue by justinfagnani** [wooorm/import-meta-resolve#29]
I use import-meta-resolve in a web server, where each request may make several calls to `moduleResolve()`. It seems useful to have an async API to unblock the main thread while resolution is performing file I/O.

**Comment by wooorm** [comment]
This project is more a copy of the node internals. So as that isn’t there, because reasons, I don’t really see mee making it

**Comment by justinfagnani** [comment]
Ah, I see. I did open https://github.com/nodejs/node/issues/54051 on Node to request an async API similar to `moduleResolve()`, so maybe if that's added it can be copied here.

**Comment by wooorm** [comment]
Nice! I’ll close this for now here then. If that goes somewhere, we can talk about it then!
