### ISSUE TITLE
how to resolve named exports?

### ISSUE THREAD

**Issue by lili21** [wooorm/import-meta-resolve#8]
```js
export { Test } from './test/lib/test.js'
```

how to resolve the `Test` module ?

**Comment by wooorm** [comment]
This is incredibly vague. Please expand your question with a ton more info...

**Comment by lili21** [comment]
Let say I have a third library - 'test-module', and this's how I use it

```js
import { foo } from 'test-module'
```

I'd like to resolve the `foo` module's path.

**Comment by wooorm** [comment]
This is still incredibly vague: https://stackoverflow.com/help/how-to-ask.

It seems to have nothing to do with this project.

**Comment by lili21** [comment]
if the source code of 'test-module' entry/main file is something like

```js
export { foo } from './lib/core/foo.js'
```

I want get the `path-to-node_modules/test-module/lib/core/foo.js` value. by import-resolve

**Comment by lili21** [comment]
Right now, I can only get the `test-module`'s path by running `resolve('test-module')`. 
But what I want is the `foo` module's path which expose by `test-module`
